### PR TITLE
Ft authenticate and authorization

### LINKED ISSUE #7: [Registration Module Backend] Authenticate and authorize users before logging in to the dashboard
**Authenticate and authorize users**
Users should be able to signup/register

**Authenticate Users**
Only authenticated users should have access to protected routes

**Authorize users**
Authorize users

### PR DESCRIPTION
**Pull request by phawazzzy**
## Description
##Please include a summary of the change and relevant motivation and context. 
This PR contains the functionalities which allows user to signup and login
It also has the functionality of protected route,...which is allow only authenticated users to access protected routes

##List any dependencies that are required for this change.
The following dependencies are installed for the above the features
  *[bcrypt version ^4.0.1](https://www.npmjs.com/package/bcrypt)
   [json-webtoken version ^8.5.](https://www.npmjs.com/package/jsonwebtoken)

Fixes #(7)

## How Has This Been Tested?
I have tested this by using postman to pass the requested data and also viewing response
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.
FRAMEWORK: NODEJS v12.16.1
LINUX DISTRO: ZORIN OS
IDE: VSCODE

## Screenshots (if applicable, else remove this line / section)
There are screenshots but i dont know how to share it here 

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by danthecm — CHANGES_REQUESTED** [review]
Try review your code to match the same file structure with the develop branch

**Comment by phawazzzy** [comment]
> Try review your code to match the same file structure with the develop branch

changes have been done, please review again, and also i did some editing to the previous files ..if this get merged, contributors should always pull develop before working

**Review by danthecm — APPROVED** [review]
Nice job @phawazzzy

**Review by dhatGuy — APPROVED** [review]

**Review by thevetdoctor — COMMENTED** [review]
Good job.
Maybe later we can be more semantic with this line below
      const token = bcrypt.generateToken(user);
using  bcrypt.generateToken to generate a jwt token may be confusing
bcrypt and jwt has different roles

well done bro

**Review by thevetdoctor — APPROVED** [review]

**Comment by phawazzzy** [comment]
I didn't use bcrypt to generate the token, I used jwt.. It is just that the file I imported where the generate token function was given the name bcrypt

**Review by chubukas — APPROVED** [review]
Nice work bro

**Pull request merged**
