### PR TITLE
Ft front end reports

### LINKED ISSUE #41: [DASHBOARD MODULE-2 (Frontend)]Design and implement an interface that accept an api  and send  reports from users per location
**Is your feature request related to a problem? Please describe.**
will show an interface that will help to solve hazards while travelling

**Describe the solution you'd like**
A user opt to make a report about incidence on their movement, different report type is provides as the case may be.

### PR DESCRIPTION
**Pull request by shammahk**
## Description
Added the reports pages for all reports, specific report and a make new report page. the pages are still underway as the api to utilize them are not available yet.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #41 

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dhatGuy — DISMISSED** [review]

**Review by danthecm — APPROVED** [review]
Good job bro @shammahk

**Review by dhatGuy — DISMISSED** [review]

**Review by danthecm — CHANGES_REQUESTED** [review]
Your code has some codacy error kindly check and fix @shammahk 
codacy 101

**Review by myquery — DISMISSED** [review]
Tested

**Review by danthecm — DISMISSED** [review]

**Review by dhatGuy — DISMISSED** [review]

**Review by thevetdoctor — APPROVED** [review]
Nice. Let's speed things up, guys!

**Review by dhatGuy — APPROVED** [review]

**Review by danthecm — APPROVED** [review]

**Pull request merged**
