### PR TITLE
profile page

### LINKED ISSUE #33: [DASHBOARD MODULE-2(Frontend)] create user profile from his details, location and activities, profile should include an avatar
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #50: [Dashboard Module 2(Frontend)] Create Profile Page....
**Create FASTA Profile page(account)**
Create a nice looking profile page for a FASTA user containing his basic details and also the user could change password and apply as a rider

### PR DESCRIPTION
**Pull request by dhatGuy**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #50  #52 

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by myquery** [comment]
It seems like you have a syntax error on your template! Pls review and fix. Good job

**Comment by dhatGuy** [comment]
> It seems like you have a syntax error on your template! Pls review and fix. Good job

Okay. I'll fix it ASAP

**Review by shammahk — CHANGES_REQUESTED** [review]
Awesome work. Please add validation to the fields using react-hook-form as in the login and signup pages.

**Review by thevetdoctor — DISMISSED** [review]
Good job. We are getting close.

**Review by myquery — DISMISSED** [review]
code clean; good job oba

**Review by danthecm — APPROVED** [review]
Great Job Bro

**Review by phawazzzy — APPROVED** [review]

**Review by shammahk — APPROVED** [review]
wonderful job.

**Review by thevetdoctor — COMMENTED** [review]
Nice. Well done

**Review by thevetdoctor — COMMENTED** [review]
Nice. Well done

**Pull request merged**
