### PR TITLE
feat: integration of front&back ends

### LINKED ISSUE #49: [FASTA Module 1(FRONTEND)] Create New Password Page
Create the new password page where the user can enter his new password

**Describe the solution you'd like**
The new password page should contain 2 input fields
- [ ] New password
- [ ] Confirm New password

### LINKED ISSUE #58: [BUG] FIX ALL MODULE 1 BUGS
**Describe the bug**
Fix all module 1 bugs on the Sign up, Login and Forgot password Pages

### PR DESCRIPTION
**Pull request by thevetdoctor**
## Description
This PR implements the userflow from signup, login to reset password, change password, and sending the relevant url links and token to the user email.

Fixes #58

## How Has This Been Tested?
A new user was able to sign up (received a welcome email)
A registered user was able to log in
A registered user was able to reset his/her password by supplying a VALID & REGISTERED email and received a changepassword link in the mail
The link redirects to the change password page (if link is VALID), or the reset password page (if link is INVALID)
The user was able to change password and received a confirmation email for password change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by danthecm — APPROVED** [review]
Great Job @thevetdoctor

**Review by danthecm — CHANGES_REQUESTED** [review]
Your code has some codacy errors kindly check and fix them @thevetdoctor 
Thanks
codacy 102

**Comment by thevetdoctor** [comment]
@danieletchie , pls check and revert. thx

**Review by danthecm — APPROVED** [review]
Nice

**Review by dhatGuy — APPROVED** [review]

**Review by myquery — APPROVED** [review]
Tested

**Comment by thevetdoctor** [comment]
Thanks so much @myquery , @danieletchie & @dhatGuy .

You motivate me!

**Review by dhatGuy — APPROVED** [review]

**Pull request merged**
