### PR TITLE
Ft nodemailer 6

### LINKED ISSUE #6: [Registration Module Backend] Send email to successful registrants using nodemailer
**Users should receive email after confirming their registration**
Users should receive email after confirming their registration

**send email using nodemailer**
Users should receive email and successfully confirming their registration

### PR DESCRIPTION
**Pull request by myquery**
## Description
The api allow users to confirm their registration, clicking a link in their email

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 6) 

## How Has This Been Tested?
branched off the develop branch and created a feature branch `ft-nodemailer-6. ` I `npm install root dev dependencies` then `cd into fasta-backend` and `npm install fasta-backend  dependencies` 

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [ x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by danthecm — CHANGES_REQUESTED** [review]
Your code has some eslinting errors kindly check them out

**Review by danthecm — APPROVED** [review]
Great Job @myquery

**Review by thevetdoctor — APPROVED** [review]
image

image


very nice job

**Review by dhatGuy — APPROVED** [review]

**Comment by chubukas** [comment]
Nice work bro

**Pull request merged**
