### PR TITLE
frontend user registration and login

### LINKED ISSUE #10: [Registration Module Frontend] Prepare Sign up and Login Pages with Validation
**Sign up Page**
The sign up pages should contain a form collecting details including 
- [x] Full Name
 - [x] Email 
- [x] Phone Number 
- [x] Password 
- [x] Confirm Password 

**Login Page**
Prepare Login page according to the UI design by Shammah 
**BOTH SIGN UP AND LOGIN PAGE SHOULD BE RESPONSIVE AND MOBILE FIRST**

### PR DESCRIPTION
**Pull request by tohbay**
## Description
This issue adds frontend user registration and login with client user data validation. 
All the dependencies required for this change can be found in `fasta-fronend/package.json` and also one dependency (`concurrently`) on the root directory

Fixes #(issue number 10)

## How Has This Been Tested?

This PR can be tested on the `ft-frontend-registration-login` branch. So endeavor to checkout to this branch and do the following:
 
1. `cd into fasta-frontend` and run `yarn install` or `npm install`  to install the frontend dependencies.
2.  `cd into fasta-backend` and run `yarn install` or `npm install` to install the backend dependencies.
3. `cd into the root directory FASTA` and run `yarn install` or `npm install`  to install the dependencies for the root directory.
4. From the root directory (FASTA) run `yarn dev` or `npm run dev` to start the application. This will start the root application, the backend server and the frontend server on the following ports:
`main-app`: `localhost:1234`
`backend`: `localhost:3000`
`frontend`: `localhost:7001`

5. Navigate to `localhost:7001/signup` for the signup page.
6. Navigate to `localhost:7001/login`  for the login page.

## Screenshots (if applicable, else remove this line / section)

Signup: 
image

Login:
image

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by myquery — APPROVED** [review]
well indented, good code organisation

**Review by chubukas — APPROVED** [review]
good coding IB

**Review by shammahk — CHANGES_REQUESTED** [review]
awesome work. please can you integrate your code using the `front-end` branch as your base. every other thing is great. Please work from the `front-end `branch.

**Comment by tohbay** [comment]
I am so sorry man, converting that feature to NextJS adds an extra learning
curve to me and I don't have the luxury of time right now.
Please you can pull what's there and see if you can fix it into that
frontend branch.
Thank you in advance

**Comment by danthecm** [comment]
We'll go with that @tobechukwuobitube

**Comment by tohbay** [comment]
Hi @CM, I don't understand what you mean.

Please can you explain?

**Comment by danthecm** [comment]
@tobechukwuobitube I mean you did a great job 
and you don't have to bother yourself about the Nextjs and fixing other things @thevetdoctor Oba can take care of that

**Comment by tohbay** [comment]
Alright, thank you

**Review by thevetdoctor — APPROVED** [review]
Nice work Tobe.
Am sharing the NextJS version shortly!

**Pull request closed without merging**
