### PR TITLE
setup mongo for fasta

### LINKED ISSUE #2: Create FASTA Database and Table
**What is your feature request related to**
This is about creating the database and table for user registration

**Describe the solution you'd like**
A Cloud Based Database is going to be created named FASTA and a users table also which will contain list of registered users info using MongoDB.
The Basic users Table will hold information including
- [ ] Full Name
- [ ] Email
- [ ] Phone Number
- [ ] Password

### PR DESCRIPTION
**Pull request by thevetdoctor**
## Description
This PR features the setup of a database for FASTA, and creation of the users table.
Mongo Atlas was set up in the cloud and a 'fasta' database was created, with a 'users' collection.
Mongoose was used to set up the schema, which comprises a user with 'fullname', 'email', phonenumber', and 'password' properties.

##Dependencies installed include:
mongoose
express
body-parser
dotenv

##DevDependencies:
nodemon

Fixes #2  

## How Has This Been Tested?
Routes for createUser, getAllUsers, and getUser were created and tested with Postman.

## Screenshots 
image

## Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [x ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by danthecm** [comment]
Nice one Oba

**Comment by phawazzzy** [comment]
@thevetdoctor you have gat some eslint error..can you have that fixed pls, you  can do so easily by installing eslint extension in your code editor...
the eslint extension would automatically pick point the error and you could fix it automatically

**Review by phawazzzy — CHANGES_REQUESTED** [review]
you need to fix all the exlint error, you just have to get exlint extension on your vscode and right click on the error red lines of the, then click on fix all auto-fixable

**Comment by thevetdoctor** [comment]
Thanks for your review @danieletchie && @phawazzzy . eslint error fixed. kindly review!

**Review by danthecm — APPROVED** [review]

**Review by danthecm — APPROVED** [review]

**Review by phawazzzy — APPROVED** [review]

**Comment by tohbay** [comment]
There has been an update to the *Develop* branch @thevetdoctor, Please `git-rebase` to update your branch then implement the DB-setup.

The database setup with MongoDB should not take more than 10 lines of code.
You have a lot of redundant code on this branch.

For example, you do not need to set up another `node-express server`, it already in the `develop` branch.

`Lines 7 and 15` in the `server.js` file are not used, that is why `ESLint` was flagging them.
Please in as much as we want things to work, we do not have to turn off the `eslint` settings.

**Comment by thevetdoctor** [comment]
> There has been an update to the _Develop_ branch @thevetdoctor, Please `git-rebase` to update your branch then implement the DB-setup.
> 
> The database setup with MongoDB should not take more than 10 lines of code.
> You have a lot of redundant code on this branch.
> 
> For example, you do not need to set up another `node-express server`, it already in the `develop` branch.
> 
> `Lines 7 and 15` in the `server.js` file are not used, that is why `ESLint` was flagging them.
> Please in as much as we want things to work, we do not have to turn off the `eslint` settings.

**Pull request closed without merging**
