### PR TITLE
added backend main folder

### LINKED ISSUE #11: Setup Backend Folder Structure
**Setup Backend Folders Structure**
Prepare the backend folder and files structure for FASTA

### PR DESCRIPTION
**Pull request by chubukas**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by phawazzzy — CHANGES_REQUESTED** [review]
nice one here @chubukas but thee are still some thing not allowing it to pass,
Please just use esllint to fix all auto fixable

**Comment by chubukas** [comment]
> nice one here @chubukas but thee are still some thing not allowing it to pass,
> Please just use esllint to fix all auto fixable

i have corrected the mistake. the test are passing now

**Review by phawazzzy — APPROVED** [review]
nice one

**Comment by tohbay** [comment]
Nice job @chubukas 👍 

However, I have a few feedback:

a) It will be nice you adhere to the use of ES6 import/export statements as the base repository is configured to work with them.

b) Since there is an *index.js* file in the *routes* folder, there is no need for separately importing the user routes into the *app.js* entry file, rather the user route should be imported inside the *routes/index.js*.

c) While I admire the *server starter* file setup, I think it is too verbose and can be reduced to aid readability and easy to understand.

d) There is *no developer experience* on the backend server setup at *fasta-backend* folder as it is difficult to know that the server is running and the port it is running on by looking at the *terminal output*

e) Endeavour to use clear and concise commit messages and also squash your commits to one commit.

Please attend to the feedback above.

**Pull request merged**
